### ISSUE TITLE
Separate main skeleton file into modules ...

### ISSUE THREAD

**Issue by andrejd** [whatsnewsaes/Skeleton-Sass#10]
... move variables from main skeleton file into _variables.scss module and put rest of source code into  _base.scss module. Main skeleton file should then include them ...

This way you can keep source code as it is and you do not have problems updating to the latest version when using skeleton as a dependency ...

**Comment by benhinchley** [comment]
You don't really need to split the variables up into a different file from my understanding, can you not just define the changed variables before `@import 'skeleton.scss'` ?

**Comment by andrejd** [comment]
Ok, you are right, that would also work, but in this case you would need to change variables inside `skeleton.scss` to use guarded assignment: `$my-constant : #fedcba !default`. 

This way, if you declare variables before `@import 'skeleton.scss'`, variables won't get redefined ....

**Comment by benhinchley** [comment]
Well that is a pretty simple change and keeps the file structure inline with the original Skeleton package.
