### ISSUE TITLE
bower.json doesn't point to main file

### ISSUE THREAD

**Issue by dizzyone** [whatsnewsaes/Skeleton-Sass#15]
Hey, I noticed that I couldn't use grunt's wiredep for this package, turns out the "main" property in bower.json doesn't point to the file. It says "skeleton.scss", however, it should say "scss/skeleton.scss". (as the file resides in the /scss directory)

**Comment by benhinchley** [comment]
Argh yeah that would be my bad, ill fix this a make a pr now

**Comment by whatsnewsaes** [comment]
Thanks @dizzyone for point this out. Thanks @benhinchley for the quick fix
