### ISSUE TITLE
Break the .scss file to pieces?

### ISSUE THREAD

**Issue by diagramatics** [whatsnewsaes/Skeleton-Sass#17]
Seems like a great way to categorize the contents, IMO.

**Comment by benhinchley** [comment]
Yeah I see the benefits of this in large projects, but seeing as most of the time, we are updating this to keep up with the css version, by copying the css version and refactoring in sass, breaking it up would just add another step in the process. Though that is just my opinion on this

**Comment by whatsnewsaes** [comment]
I tend to agree with @benhinchley. However, how would you like to see them broken up, @diagramatics?

**Comment by benhinchley** [comment]
If I was going to break it up, id break it up into base (setup things), grid, typography (would probably put in lists, tables and code stuff here), buttons, form elements & utilities

**Comment by diagramatics** [comment]
Normally I would do what @benhinchley suggests, breaking it according to the table of contents plus a variable file somewhere separate.

I might be utterly wrong since I used Skeleton just recently, but it seems like the original CSS version was meant to be edited depending on the user's likings (and not just a mere value change here and there). Breaking the SCSS file might help with it.

**Comment by benhinchley** [comment]
@diagramatics yeah that is very true, it is called _Skeleton_ for a reason, breaking it up would allow for a more custom use of the css boilerplate, would also require a lot more variables to be created to make such a thing work. That being said, I pretty much end up breaking it up for nearly every project I use this in, so wouldn't be too hard to change

**Comment by diagramatics** [comment]
Then I guess I'll hand it over to you guys. Not going to attempt anything since I'm still new to using it. Thanks!

**Comment by whatsnewsaes** [comment]
Hey guys,

put together a little project called boneless This will give us the freedom to be able to improve/expand without feeling tied down.
