### ISSUE TITLE
Create modules

### ISSUE THREAD

**Issue by rafaell-lycan** [WhatsNewSaes/Skeleton-Sass#29]
Skeleton it's a amazing and simple grid system, and that's awesome.

Maybe we could divide the files by definition like the "Table of contents" int the main file.

What you say about it?

**Comment by whatsnewsaes** [comment]
Let's get some feedback on this. I'm on the fence about this one.

**Comment by vectorsize** [comment]
+1 :)

**Comment by rafaell-lycan** [comment]
+1 :+1:

**Comment by bezin** [comment]
+1

**Comment by WhatsNewSaes** [comment]
I will add this in this weekend

**Comment by vectorsize** [comment]
yay! ^^

**Comment by WhatsNewSaes** [comment]
Thanks all.

**Comment by rafaell-lycan** [comment]
Np @WhatsNewSaes , I'm using Skeleton in my personal projects, so, if I've time to contribute with the project, why not? :smiley:

**Comment by WhatsNewSaes** [comment]
awesome @rafaell-lycan! Love the community over here. I'd like to bring these changes to Skeleton-Less as well
