### ISSUE TITLE
Suggestion - libsass integration?

### ISSUE THREAD

**Issue by tenshi13** [WhatsNewSaes/Skeleton-Sass#36]
Good day, 

Sorry to be abrupt, just found Skeleton-Sass.
Am quite happy playing around with it, and would like to contribute.

I would highly suggest libsass integration.
From experience, trading ruby sass engine with libsass is beneficial because:
- a LOT faster than ruby sass on larger projects
- does not need ruby as a dependency

The change is quite simple and easy, (I've done and tested it on local test pages)
You should be able to have a look here:
https://github.com/WhatsNewSaes/Skeleton-Sass/compare/master...tenshi13:master.add.libsass

The change is basically using:
- node-sass (the node wrapper for libsass )
- then grunt-sass (allows us to interface to node-sass via grunt)

would like to hear what you think?

regards,
Ethan HO

**Comment by WhatsNewSaes** [comment]
I like this idea. It should happen, let me see what I can do.

**Comment by WhatsNewSaes** [comment]
Could we not simply change the grunt plugin dependency to grunt-libsass? https://www.npmjs.com/package/grunt-libsass

**Comment by tenshi13** [comment]
Sweet.

I did have a look at grunt-libsass a while ago, it was not as stable as node-sass + grunt-sass.
had a look again today, it mentioned 'No Longer Maintained' at its npm page : P

**Comment by WhatsNewSaes** [comment]
gotcha. if you want to send me a PR, I'll be glad to check out your implementation.

**Comment by tenshi13** [comment]
here you go:
https://github.com/WhatsNewSaes/Skeleton-Sass/pull/37

**Comment by Sivilll** [comment]
Sorry to butt in - Im new to github and how it is used, but looking at this thread is fascinating: Someone in Australia added glue to someone's building in U.S - and here i come and copy the entire structure and places it in front of me, so i can learn how this is done. Thank you both.

**Comment by WhatsNewSaes** [comment]
The power of open source technology @Sivilll -- it's great!

I guess we can close this issue because of https://github.com/WhatsNewSaes/Skeleton-Sass/pull/37
