### ISSUE TITLE
Not displaying scandinavian letters

### ISSUE THREAD

**Issue by Sivilll** [WhatsNewSaes/Skeleton-Sass#38]
Hello. I love this repo, but when i switched my html from regular skeleton to this one, the letters "æ, ø and å" did not show. Do you know what causes it?

**Comment by WhatsNewSaes** [comment]
hmmm... not totally sure on this one. Try removing the `.editconfig` file and then add in your scandinavian letters.

**Comment by benhinchley** [comment]
the `.editorconfig` file shouldn't affect it I am pretty sure the charset is set to `utf-8` though I can't be 100% sure, so that is probably something to look at, I'll give it a look and see if I can find anything

**Comment by WhatsNewSaes** [comment]
@benhinchley I believe you are right.

@Sivilll did you get it working correctly?

**Comment by Sivilll** [comment]
Yes, that was it :) Cheers.

**Comment by Sivilll** [comment]
Yes, that was it:) Cheers
