### ISSUE TITLE
Create this as it's own bower pacakge??

### ISSUE THREAD

**Issue by benhinchley** [whatsnewsaes/Skeleton-Sass#7]
Would it be a good idea for this fork, to create it as a bower package, so we can include dependencies etc. Or should we just add in normalize.css and manage the version updates ourselves?

**Comment by whatsnewsaes** [comment]
You'll have to let me know if i'm wrong, but I think the only thing we would gain from bower is ability to download from the command line by simply typing `bower skeleton-sass` would we still have to run NPM install? or would that be done during the bower download?

**Comment by benhinchley** [comment]
Yeah that is correct, you would still have to run `npm install`, though not many bower packages have the build system in them, I guess if we were going to package this up as a bower package we would remove the grunt part to it, so people could easily pull the file into their existing workflow if they have one.

**Comment by VladShcherbin** [comment]
@whatsnewsaes add bower please, it is a must have today and takes 5 minutes to add

**Comment by andrejd** [comment]
I would suggest to at least put variables in separate file, so it would be easier to customize skeleton when using it as a dependency ...

**Comment by whatsnewsaes** [comment]
@VladShcherbin, @benhinchley I will consider adding bower sometime this weekend.

@andrejd, go ahead and make a separate issue for your variables request.

**Comment by whatsnewsaes** [comment]
So with the help of @benhinchley, we created a bower package for skeleton-sass. You can get it by typing `bower install skeleton-scss` It downloads, the bower components, however it does not include the package.json, so when I run `npm install` it obviously can't install dependancies. Thoughts from the bower experts out there?

**Comment by benhinchley** [comment]
@whatsnewsaes I excluded the `package.json` from the bower download (you can see this in the `bower.json` file) to make the package more versatile. Happy to change that so when you download the bower package it comes with the `package.json` file you supplied

**Comment by andrejd** [comment]
I think that `package.json` is needed only to develop this project and not in bower package. I assume that Skeleton-Sass will be often used as a development dependency and `skeleton.scss` will be imported into existing `sass` project where it will be compiled into `css` ...

**Comment by whatsnewsaes** [comment]
Gotcha...but that basically limits bower to only being useful when using skeleton-sass as a dependency.

**Comment by benhinchley** [comment]
@andrejd :+1: that's what I was thinking @whatsnewsaes yeah that is true, and how I see a lot of people using it but that could just be because that's how I use it

**Comment by andrejd** [comment]
well, from my perspective I see this project as a dependency. Someone can always include original `skeleton.css` to their project if needed. When it comes to tweaking, this project has great value as, at least for me, other frameworks are to bloated and you end up using only 2% of it ... 

That said, it does not hurt to have `package.json` file in it for convenience ...

**Comment by whatsnewsaes** [comment]
Yeah let's go ahead and add the package.json file. Not sure how you did this originally @benhinchley

**Comment by benhinchley** [comment]
Okay then, I'll edit the `bower.json` to keep the `package.json` file in the download
